### ISSUE TITLE
It seems that the true labels of unlabeled training set might be used while training COREG.

### ISSUE THREAD

**Issue by TaoHuang2018** [nealjean/coreg#1]
I'm a phd student and I'm doing research into semi-supervised regression now. When searching about  COREG, I find you have reproduced it in Github.
However, when I read function _compute_deltas below,
https://github.com/nealjean/coreg/blob/2ec44e2eca1989d52fb668681775c12651514b42/source/coreg.py#L144-L162
I am surprised to find that you use `y_u` in line 152 rather than `y_u_hat` in line 153 to train `h_temp`, and using `self.U_y_pool` to add to training sets in line 218 of [coreg.py.](https://github.com/nealjean/coreg/blob/master/source/coreg.py) .
https://github.com/nealjean/coreg/blob/2ec44e2eca1989d52fb668681775c12651514b42/source/coreg.py#L215-L221
Since both `y_u` and `self.U_y_pool` are parts of true labels of unlabeled training set `self.y_unlabeled` or `self.U_y`,
https://github.com/nealjean/coreg/blob/2ec44e2eca1989d52fb668681775c12651514b42/source/coreg.py#L152
https://github.com/nealjean/coreg/blob/2ec44e2eca1989d52fb668681775c12651514b42/source/coreg.py#L241-L242
  and the variable `y_u_hat`  which stores the estimated labels of unlabeled training set is mentioned only once in the file, I am doubtful whether you use the true labels of unlabeled training set in training process. In my opinion, unlabeled y shouldn't be used in training in semi-supervised learning task.

**Comment by nealjean** [comment]
Hi TaoHuang,

I think you are right -

**Comment by nealjean** [comment]
Sorry, didn't mean to close this! I think you are right btw - please feel free to submit a pull request!

**Comment by nealjean** [comment]
Hi @TaoHuang2018 I believe I've fixed the issue that you raised, please take a look!

I also made the following minor changes:
- Remove examples from the pool for regressor 2 if they have been added by regressor 1
- Updated the code to work with Python 3

Thanks for your help!

**Comment by TaoHuang2018** [comment]
Sorry for my late response, for I'm busy preparing for my final exams and projects these days.
Thank you very much for your response and I really appreciate your work!
