### ISSUE TITLE
data_utils module can't be found

### ISSUE THREAD

**Issue by Anton471** [nealjean/coreg#2]
Hi nealjean, 
thank you for the very interesting research paper and code example. 
I want to rebuild the Coreg algorithm and apply it in my current university project. 
But it seems, that the data_utils module for the function load_data can't be found anymore. 

Is there a convenient alternative to it? 

Regards, 
Anton

**Comment by nealjean** [comment]
Hey Anton - is [this](https://github.com/nealjean/coreg/blob/master/src/data_utils.py) what you're looking for?
